apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: final-pvc
  namespace: final
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: final-sc
