apiVersion: v1
kind: Secret
metadata:
    name: final-secret
    namespace: final
data:
    MYSQL_ROOT_PASSWORD: cm9vdA==
    MYSQL_DATABASE: ZW1wbG95ZWVzCg==
    MYSQL_USER: YWRtaW4K
    MYSQL_PASSWORD: YWRtaW4K
    DBUSER: YWRtaW4K
    DATABASE: ZW1wbG95ZWVzCg==
    DBHOST: ZGIK
    DBPWD: YWRtaW4K
